// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class EnemySeekerElement : MonoBehaviour
{
  public GameObject target;
  
  public void Start()
  {
    // crea una box con dimensiones 5, 1, 5, con centro en posicion bala.z + 2.5
    
    Vector3 boxCenter = new Vector3(transform.position.x, transform.position.y, transform.position.z + 7.5f);
    Bounds box = new Bounds(boxCenter, new Vector3(15, 1, 15));
    
    GameObject[] enemies = GameObject.FindGameObjectsWithTag("Enemy");
    foreach (GameObject enemy in enemies)
      { 
        if (box.Contains(enemy.transform.position))
          {
            this.target = enemy;
            break;
          }
      }
        
  }
  
      public void FixedUpdate()
      {
    
        if (target != null)
          {
            // direccion hacia el player
            Vector3 directionToPlayer = target.transform.position - transform.position;
        
            transform.forward = directionToPlayer;
            rigidbody.velocity = transform.forward * 10f;
            //rigidbody.angularVelocity = new Vector3(30, 3, 12);
          } else
            { 
              // transform.forward = new Vector3(0, 0, 1);
              rigidbody.velocity = transform.forward * 10f;
              //rigidbody.angularVelocity = new Vector3(30, 3, 12);
            }
      }
}


