// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using _r = ResourceLoader;

public class GuidedMissile : Weapon
{
  public GameObject shot;
  
  private GameObject missileParticleSystem;
  private float nextFire;
  
  public GuidedMissile(GameObject spawnObject) : base(spawnObject)
  {
    this.shot = _r.Load<GameObject>("Prefabs/Missile");
    this.spawnObject.AddComponent<AudioSource>();
    this.spawnObject.audio.clip = _r.Load<AudioClip>("Audio/missile_launch");
  }
  
  public override void Fire()
  {
    if (Time.time > nextFire)
      {
        nextFire = Time.time + fireRate;
      
        GameObject o = GameObject.Instantiate(this.shot, spawnObject.transform.position, Quaternion.Euler(0.0f, 0.0f, 0.0f)) as GameObject;
        o.AddComponent<EnemySeekerElement>();
      
        this.spawnObject.audio.Play();
      }
  }
}
