// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class SimpleGun : Weapon
{
  public GameObject shot;
  
  public float fireRate;
  private float nextFire;
  
  public SimpleGun(Transform shotSpawn) : base(shotSpawn)
  {

    
    this.shot = Resources.Load("Prefabs/Bolt") as GameObject;
    this.shot.AddComponent<AudioSource>();
    this.shot.audio.clip = Resources.Load("Audio/weapon_player") as AudioClip;
    
  }
  
  public override void Fire()
  {
    if (Time.time > nextFire)
      {
        nextFire = Time.time + fireRate;
        GameObject.Instantiate(this.shot, spawnObject.transform.position, spawnObject.transform.rotation);
        this.shot.audio.Play();
      }
  }
}


