// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public abstract class Wave : MonoBehaviour
{
  public Vector3 spawnValues;
  
  public abstract void SpawnObject(int currentIndex);
  
  protected float WrapPosition(float xMin, float xMax, float value)
  {
    float intervalLenth = xMax - xMin > 0 ? xMax - xMin : 1;
    float result = xMin + (value % intervalLenth);
    return result;
  }
}


